/* Automatically generated by mknewcmd on Tuesday 19 January 2021 08:23:56 AM IST
 * This is machine generated output. The author of mknewcmd claims no
 * copyright over the contents of this file. Where legally permitted, the
 * contents herein are donated to the public domain.
 *
 * You should apply any license and copyright that you wish to this file,
 * replacing this header in its entirety. */

#include "wc.h"
#include <ctype.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include "cmds.h"
#include "config.h"
#include "entry.h"
#include "errors.h"
#include "util.h"

static const char *cmdname = "wc";
typedef unsigned long ul;

static ul ccnt;  // chars count
static ul wcnt;  // words count
static ul lcnt;  // lines count

static ul total_ccnt = 0;  // total char counter
static ul tot_wcnt = 0;    // total word counter
static ul tot_lcnt = 0;    // total line counter

/* Dispays help for wc in various levels */
void help_cmd_wc(unsigned int level)
{
	printf("%s help for '%s'.\n", level ? EXT_HELP : SHORT_HELP, cmdname);
}

// Function for printing error messages.
static int error(int perr, const char *fmt, va_list ap)
{
	vfprintf(stderr, fmt, ap);
	if (perr)
		perror(" ");
	else
		fprintf(stderr, "\n");
	exit(1);
}

// function for printing error messages with exit status.
static int errf(const char *fmt, ...)
{
	va_list ap;

	va_start(ap, fmt);
	error(0, fmt, ap);
	va_end(ap);

	return CMD_SUCCESS;
}

// function for printing error messages with exit status and error code.
static int perrf(const char *fmt, ...)
{
	va_list ap;

	va_start(ap, fmt);
	error(1, fmt, ap);
	va_end(ap);

	return CMD_SUCCESS;
}

// print the output of the command.
static int report(const char *file, ul ccnt, ul wcnt, ul lcnt)
{
	printf("Number of lines : %6lu \nNumber of Words : %6lu \nNumber of "
	       "Chars : %6lu \nFile Name : %s\n",
	    lcnt, wcnt, ccnt, file);

	return CMD_SUCCESS;
}

// counts number of lines and number of characters.
#define COUNT(c)         \
	ccnt++;          \
	if ((c) == '\n') \
		lcnt++;

// function for fetching next word from input and return 0 on file end or error
// conditio else return 1.
static int getword(FILE *fp)
{
	int c;

	if (feof(fp))
		return 0;

	while ((c = getc(fp)) != EOF) {
		if (isalpha(c)) {
			wcnt++;
			break;
		}
		COUNT(c);
	}

	for (; c != EOF; c = getc(fp)) {
		COUNT(c);
		if (!isalpha(c))
			break;
	}

	return c != EOF;
}

// file processing.
static int counter(const char *file)
{
	FILE *fp = fopen(file, "r");

	if (!fp)
		perrf("Can't open file `%s'", file);

	ccnt = wcnt = lcnt = 0;
	while (getword(fp))
		;
	fclose(fp);

	report(file, ccnt, wcnt, lcnt);
	total_ccnt += ccnt;
	tot_wcnt += wcnt;
	tot_lcnt += lcnt;

	return CMD_SUCCESS;
}

/* Main entry point for wc, accepts an array of arguments */
int cmd_wc(char **argv)
{
	unsigned int argc;
	unsigned int i;

	for (argc = 0; argv[argc] != NULL; argc++)
		;

	if (argc < 2)
		errf("Usage: wc FILE [FILE...]");

	for (i = 1; i < argc; i++)
		counter(argv[i]);

	if (argc > 2) {
		report("Total", total_ccnt, tot_wcnt, tot_lcnt);
	}

	return CMD_SUCCESS;
}
